### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by penberg** [chiselstrike/chiselstrike#1781]
Apline Linux is great for really small Docker images, but `chiseld` currently expects `glibc` to be present. That doesn't work on Alpine, which uses musl. Let's either make `chiseld` a fully static executable or build a musl variant for Alpine.

**Comment by psarna** [comment]
@penberg I suppose you meant "or build a glibc variant for Alpine" in the description? In any case, the first suggestion about a static executable sounds better to me :)

**Comment by psarna** [comment]
I tried `cargo build --release --target x86_64-unknown-linux-musl`, but unfortunately it fails with

```
  cargo:rustc-link-lib=static=rusty_v8
  download lockfile: "/home/sarna/repo/chiselstrike/target/x86_64-unknown-linux-musl/release/build/lib_download.fslock"
  static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.51.0/librusty_v8_release_x86_64-unknown-linux-musl.a
  cargo:rustc-link-search=/home/sarna/repo/chiselstrike/target/x86_64-unknown-linux-musl/release/gn_out/obj
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.51.0/librusty_v8_release_x86_64-unknown-linux-musl.a
  Downloading https://github.com/denoland/rusty_v8/releases/download/v0.51.0/librusty_v8_release_x86_64-unknown-linux-musl.a...
  HTTP Error 404: Not Found
  Python downloader failed, trying with curl.
```
, because the build system wants to download this static library, but it's not prebuilt in the denoland/rusty_v8 repo

**Comment by psarna** [comment]
https://github.com/denoland/rusty_v8/issues/49

**Comment by psarna** [comment]
@penberg I ended up building on top of `frolvlad/alpine-glibc` image. It looks random, but that's what deno uses for its slimmed down alpine image (looks like they *really* didn't want to pursue building a musl flavor :) ) - https://github.com/denoland/deno_docker/blob/3c0d76c1cd37fc30f667a7865c1f4c136f782a81/alpine.dockerfile#L16 .

glibc only weights ~5MiB in there, and still the resulting image is 468MiB, compared to 578 from node:18-slim. The difference isn't that vast compared to the original, because `node_modules` itself weighs 280MiB, and there's only so much we can do to minimize the overhead of the operating system. Still, I guess 102MiB is decent enough to justify a pull request.
